namespace:

kafka:
  name: kafka
  authentication:
    saslMechanism: SCRAM-SHA-512
  authorization: simple

prometheus:
  subscription:
    channel: beta
    installPlanApproval: Automatic
    name: rhods-prometheus-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    argocd:
      enabled: true
      syncwave: "-1"