nameOverride: ""
fullnameOverride: ""

image: 
  repository: quay.io/cloud-architecture-workshop/order-db
  pullPolicy: IfNotPresent
  tag: latest

podSecurityContext: 
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

podAnnotations: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""

pgsql:
  user: ordermgr
  password: ordermgr
  database: orders

globexDb:
  host: globex-db
  secret: globex-db

argocd:
  enabled: true
  syncwave: "-2"
