apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order-aggregator.name" . }}
  labels:
    {{- include "order-aggregator.labels" . | nindent 4 }}
    app.openshift.io/runtime: quarkus
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "order-aggregator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "order-aggregator.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "order-aggregator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                secretKeyRef:
                  key: bootstrapServer
                  name: {{ .Values.kafka.secret }}
            - name: KAFKA_SECURITY_PROTOCOL
              valueFrom:
                secretKeyRef:
                  key: securityProtocol
                  name: {{ .Values.kafka.secret }}
            - name: KAFKA_SASL_MECHANISM
              valueFrom:
                secretKeyRef:
                  key: saslMechanism
                  name: {{ .Values.kafka.secret }}
            - name: KAFKA_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  key: saslJaasConfig
                  name: {{ .Values.kafka.secret }}          
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /deployments/config
              name: config
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "order-aggregator.name" . }}
