apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-aggregator.name" . }}
  labels:
    {{- include "order-aggregator.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    quarkus.kafka-streams.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVER}

    quarkus.kafka-streams.security.protocol=${KAFKA_SECURITY_PROTOCOL}
    quarkus.kafka-streams.sasl.mechanism=${KAFKA_SASL_MECHANISM}

    quarkus.kafka-streams.sasl.jaas-config=${KAFKA_SASL_JAAS_CONFIG}

    quarkus.kafka-streams.application-id={{ .Values.kafka.streams.applicationId }}

    quarkus.kafka-streams.topics={{ .Values.kafka.streams.topics }}

    quarkus.kafka-streams.commit.interval.ms={{ .Values.kafka.streams.commitIntervalMs }}

    kafka-streams.replication.factor={{ .Values.kafka.streams.replicationFactor }}

    topic.order-change-event={{ .Values.kafka.topic.orderChangeEvent }}
    topic.lineitem-change-event={{ .Values.kafka.topic.lineItemChangeEvent }}
    topic.aggregate-order={{ .Values.kafka.topic.aggregatedOrder }}
