apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cashback-connector.name" . }}
  labels:
    {{- include "cashback-connector.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    camel.component.kafka.brokers=${KAFKA_BOOTSTRAP_SERVER}

    camel.component.kafka.securityprotocol=${KAFKA_SECURITY_PROTOCOL}
    camel.component.kafka.saslmechanism=${KAFKA_SASL_MECHANISM}

    camel.component.kafka.sasljaasconfig=${KAFKA_SASL_JAAS_CONFIG}
    
    quarkus.datasource.cashback.jdbc.url=${DATASOURCE_JDBC_URL}
    quarkus.datasource.cashback.username=${DATASOURCE_USERNAME}
    quarkus.datasource.cashback.password=${DATASOURCE_password}

    kafka.customer.topic.name={{ .Values.kafka.topic.customer }}
    kafka.order.topic.name={{ .Values.kafka.topic.order }}

    cashback-service.url=http://{{ .Values.cashbackService.service }}:8080/expense

    kafka.customer.consumer.group={{ .Values.kafka.consumerGroup.customer }}
    kafka.order.consumer.group={{ .Values.kafka.consumerGroup.order }}
